name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    name: Publishing binary for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos-intel, macos-arm64, ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - build: macos-arm64
            os: macos-latest
            artifact_prefix: macos-arm64
            target: aarch64-apple-darwin
            binary_postfix: ''
          - build: macos-intel
            os: macos-latest
            artifact_prefix: macos-intel
            target: x86_64-apple-darwin
            binary_postfix: ''
          - build: ubuntu-latest
            os: ubuntu-latest
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - build: windows-latest
            os: windows-latest
            artifact_prefix: windows
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Installing needed macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install openssl@1.1
      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq pkg-config libssl-dev
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.build }}-cargo-cd-${{ hashFiles('**/Cargo.lock') }}
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.target }}
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          BINARY_NAME=prosemd-lsp${{ matrix.binary_postfix }}
          RELEASE_NAME=prosemd-lsp-${{ matrix.artifact_prefix }}${{ matrix.binary_postfix }}
          strip $BINARY_NAME
          cp $BINARY_NAME $RELEASE_NAME
          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME > $RELEASE_NAME.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/prosemd-lsp-${{ matrix.artifact_prefix }}${{ matrix.binary_postfix }}
            target/${{ matrix.target }}/release/prosemd-lsp-${{ matrix.artifact_prefix }}${{ matrix.binary_postfix }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-cargo:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.build }}-cargo-publish-${{ hashFiles('**/Cargo.lock') }}
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq pkg-config libssl-dev
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }} --allow-dirty

  publish-vscode:
    name: Publish VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.build }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.build }}-node-
      - name: npm install
        working-directory: ./vscode
        run: npm ci
      - id: metadata
        run: |
          METADATA=$(cargo metadata --no-deps)
          echo "::set-output name=crate::$METADATA"
      - name: Package to VSCode Extension
        working-directory: ./vscode
        env:
          VSCE_PAT: ${{ secrets.VSCODE_API_KEY }}
        run: |
          ./node_modules/.bin/vsce package --out prosemd-vs.vsix
      - name: Publish to VSCode Marketplace
        working-directory: ./vscode
        env:
          VSCE_PAT: ${{ secrets.VSCODE_API_KEY }}
          VERSION: ${{ fromJson(steps.metadata.outputs.crate).packages[0].version }}
        run: |
          ./node_modules/.bin/vsce publish $VERSION
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vscode/prosemd-vs.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
